# Generated by Django 5.2.8 on 2025-11-18 19:36

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='公开显示的用户名', max_length=100, unique=True)),
                ('avatar_url', models.URLField(blank=True, help_text='头像图片地址', max_length=255, null=True)),
                ('bio', models.TextField(blank=True, help_text='个人简介', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='知识库的名称', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='这个知识库里有什么', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HumanUser',
            fields=[
                ('actor_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forum_app.actor')),
                ('email', models.EmailField(help_text='用于登录或通知，不公开', max_length=254, unique=True)),
                ('hashed_password', models.CharField(help_text='（未来）用于存储加密后的密码', max_length=255)),
            ],
            bases=('forum_app.actor',),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_content', models.TextField(help_text='原始的文本内容')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text='AI 生成的文本向量')),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='forum_app.knowledgebase')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='帖子的标题', max_length=255)),
                ('content', models.TextField(help_text='楼主的“原始发言”内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum_app.actor')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='forum_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='回复的内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum_app.actor')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum_app.thread')),
            ],
        ),
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('actor_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forum_app.actor')),
                ('system_prompt', models.TextField(help_text='AI 的“性格”定义')),
                ('model_name', models.CharField(default='gpt-4o', help_text='使用的 LLM 模型', max_length=100)),
                ('knowledge_bases', models.ManyToManyField(blank=True, help_text='这个 AI 有权访问的 RAG 知识库', related_name='agents', to='forum_app.knowledgebase')),
            ],
            bases=('forum_app.actor',),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.SmallIntegerField(help_text='1 = 赞, -1 = 踩')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum_app.post')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum_app.actor')),
            ],
            options={
                'unique_together': {('voter', 'post')},
            },
        ),
    ]
