# Generated by Django 5.2.8 on 2025-11-19 03:06

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='ai_generating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actor',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='knowledge_bases',
            field=models.ManyToManyField(blank=True, related_name='agents', to='forum_app.knowledgebase'),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='model_name',
            field=models.CharField(default='gemini-2.5-pro', max_length=100),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='system_prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
        migrations.AlterField(
            model_name='document',
            name='text_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='humanuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='humanuser',
            name='hashed_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vote',
            name='direction',
            field=models.SmallIntegerField(),
        ),
    ]
