# Generated by Django 5.2.8 on 2025-11-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_app", "0002_thread_ai_generating_alter_actor_avatar_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="thread",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterField(
            model_name="aiagent",
            name="model_name",
            field=models.CharField(default="gemini-2.5-flash", max_length=100),
        ),
    ]
